# =================================
# = Server
# =================================
server:
  port: 8080
  servlet:
    context-path: /v1

# =================================
# = Spring
# =================================
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
    type: com.zaxxer.hikari.HikariDataSource
  mail:
    host: smtp.gmail.com
    username:
    password:
    from:
    properties:
      mail.transport.protocol: smtp
      mail.smtp.port: 587
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

# =================================
# = Logging
# =================================
logging:
  level:
    org.springframework: INFO
    org.flywaydb: INFO

# =================================
# = RealMeet
# =================================
realmeet:
  allocations:
    maxFilterLimit: 50
  email:
    templates:
      allocationCreated:
        subject: New room booking created
        templateName: allocation-created.html
      allocationUpdated:
        subject: Room booking modified
        templateName: allocation-updated.html
      allocationDeleted:
        subject: Room booking deleted
        templateName: allocation-deleted.html
      allocationReport:
        subject: Room booking report
        templateName: allocation-report.html
